{{- if .Values.oauth.enabled }}
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: {{ include "ops-buddy.fullname" . }}-oauth-client
  labels:
    {{- include "ops-buddy.labels" . | nindent 4 }}
grantMethod: auto
secret: {{ .Values.oauth.clientSecret }}
redirectURIs:
  - {{ .Values.oauth.redirectUri }}
{{- end }}

