{{- if .Values.global.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ops-buddy.fullname" . }}-pull-secret
  labels:
    {{- include "ops-buddy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecret }}
{{- end }}
